### ISSUE TITLE
How can templates get inserted into the JSON for the webhook?

### ISSUE THREAD

**Issue by ertechdesign** [HCookie/Webhook-Service-home-assistant#1]
Hello,

Thank you for an amazing plugin, it works like a charm.

My problem is I don't know how to insert templates into the Webhook. I'm not particularly good with HA templates or Python, so I apologise if this question is completely stupid. I've tried something like this but it seems the resulting type is not a string:

```
service: webhook_service.basic_webhook
data:
  webhook: >-
    https://mywebhookurl.domain/webhookpath?token=something
  json: "{\"state\": \"{{ states.sun.sun.attributes.elevation }}\" }"
```

I'm getting the following error in traces:
`the JSON object must be str, bytes or bytearray, not Wrapper`

Is there any chance an example of working template is shared?

Thank you very much for your help!

**Comment by ThatProgrammerr** [comment]
I experienced the same thing and ended up passing it as URL parameters instead. You could try ``jsonObj`` as it seems that's an option in yml.

**Comment by fuatakgun** [comment]
@ThatProgrammerr can you explain more please :)

**Comment by ThatProgrammerr** [comment]
> @ThatProgrammerr can you explain more please :)

It's been a while but this is how I currently use it. 

```
metadata: {}
data:
  webhook: http://0.0.0.0:3000/api/endpoint
  json: "{\"val1\": \"arg1\", \"val2\": \"arg2\"}"
action: webhook_service.basic_webhook
```

**Comment by ThatProgrammerr** [comment]
Furthermore, here is my `services.yaml` - I believe I made changes. 

```yaml

basic_webhook:
  description: Service Provider to use Webhooks
  fields:
    webhook:
      name: Webhook
      description: Webhook url
      required: true
      selector:
        text:
    json:
      name: Json Data
      description: Json Data To Send
      selector:
        text:
    jsonObj:
      name: Json Data
      description: Json Object To Send
      selector:
        text:
    username:
      name: Username
      description: Username
      selector:
        text:
    password:
      name: Password
      description: Password
      selector:
        text:
discord_webhook:
  description: Service Provider to use Discord Webhooks
  fields:
    webhook:
      name: Discord Webhook
      description: Discord Webhook url
      required: true
      selector:
        text:
    content:
      name: Content 
      description: Message Content
      selector:
        text:
    json:
      name: Json Data
      description: Json String To Send
    jsonObj:
      name: Json Data
      description: Json Object To Send

```

...and just in case, here is my init file. 
```yaml 

import logging
import requests 
import json

DOMAIN = "webhook_service"
_LOGGER = logging.getLogger(__name__)


SERVICE_SEND = "basic_webhook"

def setup(hass, config):
    def send_basic_webhook(call):
        data = call.data.copy()
        # if exists json, send json string
        if "json" in data:
            jsondata = json.loads(data["json"])
        # if exists jsonObj, stringify jsonObj then send it
        elif "jsonObj" in data:
            jsondata = data["jsonObj"]
        else:
            jsondata = {}
        # BASIC authenticate
        auth = None
        if "username" in data and "password" in data:
            auth = (data["username"], data["password"])
        result = requests.post(data["webhook"], json = jsondata, auth = auth)
        _LOGGER.warn('Received data', data["webhook"])

    hass.services.register(DOMAIN, SERVICE_SEND, send_basic_webhook)

    return True
```
