### ISSUE TITLE
How to include an image

### ISSUE THREAD

**Issue by FredBouillon** [HCookie/Webhook-Service-home-assistant#7]
I'm struggling to add an image to my message i want to post to discord.

Here is the yaml i'm using in an automation: 

```
action: webhook_service.discord_webhook
metadata: {}`
data:
  webhook: >-myWebhook
  title: myTitle
  description: myDescription
  image: 
    url: /home/pi/docker/homeAssistant/data/www/snapshots/g4_doorbell_snapshot.jpg
```

It works without the image but fails whenever I include it. Tried numerous different syntax but all seem to fail.
Could anybody point me in the right direction or give me some examples?

Thanks!
